name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Project's main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub # Selected container registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t spark-df-batch-processing-java -f Build/local/dockerfile .

      - name: Tag Docker Image
        run: docker tag spark-df-batch-processing-java:latest spark-df-batch-processing-java:latest

      - name: Push Docker Image
        run: docker push spark-df-batch-processing-java:latest

